package io.github.kilian51147;

import java.util.HashMap;
import java.util.Map;

public enum Language
{
    AFAR("aa"),
    ABKHAZIAN("ab"),
    AFRIKAANS("af"),
    AMHARIC("am"),
    ARABIC("ar"),
    ASAMESE("as"),
    AYMARA("ay"),
    AZERBAIJANI("az"),
    BASHKIR("ba"),
    BELARUSIAN("be"),
    BULGARIAN("bg"),
    BIHARIC("bh"),
    BISLAMIC("bi"),
    BENGALI("bn"),
    TIBETAN("bo"),
    BRETON("br"),
    CATALAN("ca"),
    CORSICAN("co"),
    CZECH("cs"),
    WELSH("cy"),
    DANISH("da"),
    GERMAN("de"),
    DZONGKHA("dz"),
    GREEK("el"),
    ENGLISH("en"),
    ESPERANTO("eo"),
    SPANISH("es"),
    ESTONIAN("et"),
    BASQUE("eu"),
    PERSIAN("fa"),
    FINNISH("fi"),
    NAVOSAVAKAVITI("fl"),
    FAROESE("fo"),
    FRENCH("fr"),
    FRISIAN("fy"),
    IRISH("ga"),
    SCOTTISHGAELIC("gd"),
    GALICIAN("gl"),
    GUARANI("gn"),
    GUJARATIC("gu"),
    HAUSA("ha"),
    HEBREW("he"),
    HINDI("hi"),
    CROATIAN("hr"),
    HUNGARIAN("hu"),
    ARMENIAN("hy"),
    INTERLINGUE("ie"),
    INUPIAK("ik"),
    ICELANDIG("is"),
    ITALIAN("it"),
    INUKTITUT("iu"),
    JAPANESE("ja"),
    YDDISH("ji"),
    JAVANESE("jv"),
    GEORGIAN("ka"),
    KAZAKH("kk"),
    KALAALLISUT("kl"),
    CAMBODIAN("km"),
    CANADA("kn"),
    KOREAN("ko"),
    KASHMIRI("ks"),
    KURDISH("ku"),
    KYRGYZ("ky"),
    LATIN("la"),
    LINGALA("ln"),
    LAOTIAN("lo"),
    LITHUANIAN("lt"),
    LATVIAN("lv"),
    MALAGASY("mg"),
    MAORI("mi"),
    MACEDONAIN("mk"),
    MALAYSALAM("ml"),
    MONGOLIAN("mn"),
    MOLDAVIAN("mo"),
    MARATHI("mr"),
    MALAYSIAN("ms"),
    MALTESE("mt"),
    BURMESE("my"),
    NAURUAN("na"),
    NEPALESE("ne"),
    DUTCH("nl"),
    NORWEGIAN("no"),
    OCCITAN("oc"),
    OROMO("om"),
    ORIYA("or"),
    PUNDJAB("pa"),
    POLISH("pl"),
    PASHTO("ps"),
    PORTUGUESE("pt"),
    QUECHUA("qu"),
    ROMANSH("rm"),
    KIRUNDIAN("rn"),
    ROMANIAN("ro"),
    RUSSIAN("ru"),
    KIJARWANDA("rw"),
    SANSKRIT("sa"),
    ZINTI("sd"),
    SANGO("sg"),
    SERBOCROATIAN("sh"),
    SINHALA("si"),
    SLOVAK("sk"),
    SLOVENIAN("sl"),
    SAMOAN("sm"),
    SCANDINAVIAN("sn"),
    SOMALI("so"),
    ALBANIAN("sq"),
    SERBIAN("sr"),
    SWAZILAND("ss"),
    SESOTHIC("st"),
    SUDANESE("su"),
    SWEDISH("sv"),
    SWAHILI("sw"),
    TAMIL("ta"),
    TEGULU("te"),
    TAJIK("tg"),
    THAI("th"),
    TIGRINYA("ti"),
    TURKMEN("tk"),
    TAGALOG("tl"),
    SEZUAN("tn"),
    TONGAN("to"),
    TURKISH("tr"),
    TSONGAN("ts"),
    TATAR("tt"),
    TWI("tw"),
    UYGHUR("ug"),
    UKRAINIAN("uk"),
    URDU("ur"),
    UZBEK("uz"),
    VIETNAMESE("vi"),
    WOLOF("wo"),
    XHOSA("xh"),
    YIDDISH("yi"),
    JORUBA("yo"),
    ZHUANG("za"),
    CHINESE("zh"),
    ZULU("zu");


    static Map<String, Language> lang = new HashMap<>();

    String identifier;

    Language(String identifier)
    {
        this.identifier = identifier;
    }

    public String getIdentifier()
    {
        return identifier;
    }

    public static Language getLanguage(String identifier)
    {
        return lang.get(identifier);
    }
}
